language: rust

rust:
  - stable
  - nightly

addons:
  chrome: stable
  apt:
    packages:
      - libnss3

os:
  - linux
  - osx

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sysctl kernel.unprivileged_userns_clone=1    ; fi
  - "export DISPLAY=:99.0"
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start    ; fi
  - set -e
  - export RUSTFLAGS="-D warnings"
  - if [ "$TRAVIS_RUST_VERSION" != "nightly" ]; then
    rustup self update &&
    rustup component add rustfmt clippy &&
    cargo clippy --version;
    fi

cache:
  cargo: true
  directories:
    - $HOME/.local/share/
    - $HOME/Library/Application Support/

script:
  - if [ "$TRAVIS_RUST_VERSION" != "nightly" ]; then
    cargo fmt --all -- --check &&
    cargo clippy --all --tests --examples;
    fi
  - env RUST_BACKTRACE=1 RUST_LOG=headless_chrome=trace cargo test -- --nocapture
  - if [ "$TRAVIS_RUST_VERSION" = "nightly" ]; then
    cargo test --doc --features nightly README;
    fi
